set nocompatible " Be iMproved

" Grab plug.vim if it does not exist
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin()

Plug 'airblade/vim-gitgutter'
Plug 'alvan/vim-php-manual'
Plug 'bling/vim-airline'
Plug 'christoomey/vim-tmux-navigator'
Plug 'corntrace/bufexplorer'
Plug 'diepm/vim-rest-console'
Plug 'digitaltoad/vim-jade'
Plug 'editorconfig/editorconfig-vim'
Plug 'edkolev/tmuxline.vim'
Plug 'francoiscabrol/ranger.vim'       " use ,f to browse file system
Plug 'godlygeek/tabular'
Plug 'jiangmiao/auto-pairs'
Plug 'joonty/vdebug'
Plug 'kien/ctrlp.vim'
Plug 'moll/vim-bbye'                   " close buffer without closing the split it lives in
Plug 'evidens/vim-twig'
Plug 'NickLaMuro/vimux'
Plug 'plasticboy/vim-markdown'
Plug 'pld-linux/vim-syntax-vcl'
Plug 'quafzi/vim-flow-diagram'         " preview for flow diagrams
Plug 'quafzi/snipmate.vim'
Plug 'rhysd/committia.vim'             " add status and diff view to commit buffers
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tobyS/pdv'
Plug 'tobyS/vmustache'
Plug 'tpope/vim-abolish'               " :%Subvert/facilit{y,ies}/building{,s}/g
Plug 'tpope/vim-fugitive'              " Git integration
Plug 'tpope/vim-projectionist'
Plug 'wavded/vim-stylus'               " stylus syntax highlighting
Plug 'xavierchow/vim-sequence-diagram' " preview for sequence diagrams

call plug#end()

runtime functions.vim
runtime settings.vim

" include settings folder recursive (!)
runtime! settings/*.vim

runtime keybindings.vim

" enable per-project configuration files
set exrc
" disable unsafe commands in your project-specific .vimrc
" This will prevent :autocmd, shell and write commands from being run inside
" project-specific .vimrc files unless they’re owned by you.
set secure
