# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="ys"
ZSH_THEME="bullet-train"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(archlinux git composer tmux tmuxinator z docker docker-compose symfony2 git-open sudo pass zsh-autosuggestions)
#plugins+=(stash-aware)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:vendor/bin:/home/thomas/.gem/ruby/2.3.0/bin

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

alias ....="cd ../../.."
alias .....="cd ../../../.."
#alias ai="_ aptitude install"
alias go="gnome-open"

export EDITOR=vim

export TERM="xterm-256color"

source ~/.nvm/nvm.sh

# e.g. you can use gsq 3 to squash the last three commits to one.
function gsq(){
  git reset --soft HEAD~$1 && \
  git commit --edit -m \
  "$(git log --format=%B --reverse HEAD..HEAD@{1})"
}

# disable glob expansion for the puli command
alias puli='set -f;puli';puli(){ command puli "$@";set +f; }

alias s='npm start'
alias t='npm test'
alias tea="sleep 300; play /usr/share/sounds/ubuntu/stereo/phone-incoming-call.ogg; notify-send -u critical 'Tee ist fertig...'"
alias dc="docker-compose"
alias mack="ack --ignore-dir=var"
alias mux="tmuxinator"

. /etc/profile.d/vte.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.my-ssh-agent
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
  eval "$(<~/.my-ssh-agent)"
fi

